### ISSUE TITLE
`chk_url`?

### ISSUE THREAD

**Issue by NewGraphEnvironment** [poissonconsulting/chk#126]
Guessing this is not the package for a function that checks to see if a url is valid if it would introduce more dependencies (ex. `httr`)?

See details at
https://github.com/NewGraphEnvironment/rfp/issues/2

might be ways around the dependency too I guess.  If so - is this the place for this?

Loving `chk` - thank you!

**Comment by joethorley** [comment]
We've discussed as a team and its not straightforward to check if a url is valid because its possible to "connect" to any url whether or not it exists (consider `url("https://www.oueou")`) and often one a url may no longer be valid but the website will serve up a 404 page. So unless we can come up with a quick and simple test I think it will add to much complexity to the package.

**Comment by NewGraphEnvironment** [comment]
Ah - good points! Thanks for considering and responding
