### ISSUE TITLE
chk_s3_class() allows checking for multiple classes

### ISSUE THREAD

**Issue by krlmlr** [poissonconsulting/chk#74]
`inherits()` is really `rlang::inherits_any()`; should we document that and fix the error output?

``` r
chk::chk_s3_class(1, c("tbl_df", "data.frame"))
#> Error: `1` must inherit from S3 class 'tbl_df'`1` must inherit from S3 class 'data.frame'.
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by joethorley** [comment]
I think its ok because

The [documentation](https://poissonconsulting.github.io/chk/reference/chk_s3_class.html) indicates that it
```r
Checks inherits from S3 class using

!isS4(x) && inherits(x, class)
```
which is unambiguous and that the `class` argument should be a

```r
A string specifying the class.
```

Note checking the values of arguments to chk functions is against the philosophy of the package which states that

> As the chk_ (and vld_) functions are not expected to be directly exposed to users they don’t check any of their arguments (other than the object of interest of course!) to ensure that they are as fast as possible.
